### ISSUE TITLE
With new ATD, setup is broken due to Radius

### ISSUE THREAD

**Issue by titom73** [arista-netdevops-community/atd-avd#4]
With the new ATD setup a radius server has been configured in the top container meaning that when AVD configures management in a VRF, authentication is broken.

```
aaa group server radius <rad-name>
   server 192.x.x.x
```

Reported by @mpergament

**Comment by mthiel117** [comment]
@titom73 solved this by adding:

radius_servers:
  - host: 192.168.0.1
    vrf: MGMT
    key: 0207165218120E

aaa_server_groups:
  - name: atds
    type: radius
    servers:
      - server: 192.168.0.1
        vrf: MGMT

to atd-avd/atd-inventory/group_vars/ATD_LAB.yml.  I think this can be closed.
